FROM node:20-alpine

WORKDIR /app

COPY starpi-app/package*.json ./

RUN npm install --production

COPY starpi-app .

RUN npm run build

ENV NODE_ENV=production

EXPOSE 1337

CMD ["npm","run","start"]
